CREATE DATABASE IF NOT EXISTS notes_db;
USE notes_db;

DROP TABLE IF EXISTS notes;

CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
